/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package controle.equipamentos;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello Girls!");
    }
}
